WIP: Add MemPool CPU
pulp-platform/snitch-llvm pull request #13
Opened 2021-06-23 15:32 UTC by SamuelRiedel

Define a mempool CPU target and add a scheduling model.

2021-06-24 06:42 UTC, noah95 requested changes

2021-06-24 06:42 UTC, noah95 commented on llvm/lib/Target/RISCV/RISCVSystemOperands.td
> +def TRACE : SysReg<"trace", 0x7D0>;
Perhaps wrap this in a `let Predicates = [] in {` to only define it if mempool is defined? Does this correlate to a custom extension? Then we could read a `HasExtXXX` and define this extension and add it also to the features of the mempool processor model

2021-06-25 08:15 UTC, SamuelRiedel commented on llvm/lib/Target/RISCV/RISCVSystemOperands.td
> +def TRACE : SysReg<"trace", 0x7D0>;
Good idea. I looked into it and could not find a way around adding a new extension. But it somehow is a new extension, although a tiny one (for now).

2021-06-25 09:12 UTC, noah95 commented on llvm/lib/Target/RISCV/RISCVSystemOperands.td
> +def TRACE : SysReg<"trace", 0x7D0>;
This looks good now, thanks

2021-06-25 09:13 UTC, noah95 approved these changes

2021-06-25 09:14 UTC, merged